name: TheShipItems
author: Richard Stöckl
version: 0.0.3-NEPTUNIUM
main: io.github.praeluceantboreus.theshipitems.main.TheShipItemsPlugin
commands:
  tsi:
    usage: /tsi
    description: main command